# --- General Settings ---
general_settings:
  data_dir: "/home/max/master_ths/data/GAPD"
  gcg_executable: "/home/max/gcg/build/gcg-linux-release/bin/gcg"
  weights_filename: "gaptest1.pth"
  num_cores: 5
  gpu_batch_size: 20
  random_seed: 45

# --- Split Parameters ---
split_parameters:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# --- Duals Generation Script Settings ---
duals_generation_settings:
  process_splits: False
  prefix_filter: ""
  generate_subopt: True
  subopt_percent: 0.995
  generate_random: True
  random_gauss_sigma: 5.0
  multicore_solving: False
  max_iters: 400
  initial_step_size: 5.0
  no_improve_limit: 10
  step_size_shrink: 0.5
  tolerance: 1.0e-6

# --- Model Architecture ---
model_architecture:
  feature_embedding_size: 16
  # The input dimension (4) and final output dimension (feature_embedding_size) are automatically added
  encoder_mlp_dims: [64]
  # The input (2 * feature_embedding_size) and output (feature_embedding_size) dimensions are dynamically added
  gnn_mlp_dims: [128]
  # The input (feature_embedding_size) and output (1) dimensions are dynamically added
  decoder_mlp_dims: [64]
  num_message_passing_layers: 2
  dropout: 0.3

# --- Training Parameters ---
training_parameters:
  load_pretrained: True
  learning_rate: 2e-5
  epochs: 100
  evaluate_validation_loss: True
  evaluate_validation_every_n_epochs: 25
  use_gradient_clipping: True
  gradient_clipping_max_norm: 80.0
  use_lr_scheduler: True
  lr_scheduler_factor: 0.3 # multiplicative factor applied to the learning rate when patience runs out
  lr_scheduler_patience: 20 #  number of epochs the scheduler will wait for the loss to improve before it reduces the learning rate
  plot_min_gap_closed: 65.0
  use_random_subset: False
  random_subset_ratio: 0.3
  plot_every_n_epochs: 1
  
  scip_settings:
    disable_presolve: False
    disable_heuristics: False
    mip_gap: 0.01

  caching_settings:
    cache_graph: True
    cache_lag_relax: False  # Cache SCIP LagrangianRelaxation objects in worker processes

# --- Feature Extraction ---
feature_extraction:
  presolving_maxrounds: 0

# --- Prediction Script Parameters ---
prediction_parameters:
  timeout: 3600
  lpfile_subdir: ""
  dualvalue_type: "optimal"
  experiment_json_name: "opt.json"
  skip_prediction: True
  only_with_prefix: "gapdcstm_40_400_4"  # Only instances with this prefix are processed. If empty, all are processed.
  
  gcg_settings:
    use_custom_duals: True
    disable_heuristics: True
    disable_presolving: True
    disable_separating_cliques: True
    disable_subprob_presolve_heur: True
    masterpricer_stabilization: False
    solve_root_only: True
    use_smoothing: True
    smoothing_weight_start: 0.99
    smoothing_weight_factor: 0.4
    smoothing_weight_min: 0.01
    smoothing_improvement_threshold: 200.0
    n_perturbation_rounds: 0
    perturbation_percent: 0.007
    add_round_0_columns: False
    large_log: False
    use_bigm_artificials: False
    bigm_value: 1000000.0
    obj_epsilon: 0


# --- Visualization Script Settings ---
visualization_settings:
  experiment_files:
    -  "raw.json"
    -  "opt.json"
    -  "opt_pert.json"
    -  "opt_raw.json"
    -  "subopt.json"
    -  "raw_stab.json"
    -  "rand.json"
    -  "opt_init_c.json"



