# --- Prediction Script Parameters ---
prediction_parameters:
  timeout: 3600
  lpfile_subdir: ""
  dualvalue_type: "optimal"
  experiment_json_name: "opt.json"
  skip_prediction: True
  only_with_prefix: "gapdcstm_40_400_4"  # Only instances with this prefix are processed. If empty, all are processed.
  
  gcg_settings:
    use_custom_duals: True
    disable_heuristics: True
    disable_presolving: True
    disable_separating_cliques: True
    disable_subprob_presolve_heur: True
    masterpricer_stabilization: False
    solve_root_only: True
    use_smoothing: True
    smoothing_weight_start: 0.99
    smoothing_weight_factor: 0.4
    smoothing_weight_min: 0.01
    smoothing_improvement_threshold: 200.0
    n_perturbation_rounds: 0
    perturbation_percent: 0.007
    add_round_0_columns: False
    large_log: False
    use_bigm_artificials: False
    bigm_value: 1000000.0
    obj_epsilon: 0
