# --- General Settings ---
general_settings:
  data_dir: "/home/max/master_ths/data/GAPD"
  gcg_executable: "/home/max/gcg/build/gcg-linux-release/bin/gcg"
  weights_filename: "gaptest1.pth"
  num_cores: 5
  gpu_batch_size: 20
  random_seed: 45
